#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

import os, shutil
Import( 'baseEnv', 'buildOS' )

aliases = [
    'timeSampleExt',
    'exceptSampleExt',
]

dirs = [
    'Time',
    'Except',
]

SConscript( dirs=dirs )

Alias( 'sampleExts', aliases )
