#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir' )

exceptSampleExtEnv = extsEnv.Clone()
exceptSampleExt = exceptSampleExtEnv.SharedLibrary( 'ExceptSample', Glob('*.cpp') ),
exceptSampleManifest = exceptSampleExtEnv.File( 'ExceptSample.fpm.json' ),
exceptFiles = [exceptSampleManifest, exceptSampleExt]

Return( 'exceptFiles' )
