#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'env' );
baseEnv = env.Clone()
baseEnv.Append(LIBS = ['pthread','dl'])
Export( 'baseEnv' );

SConscript( dirs=['RC','JSON'] )
