#
# Copyright 2010-2011 Fabric Technologies Inc. All rights reserved.
#

Import( 'extsEnv', 'fabricExtsDistDir' )

timeSampleExtEnv = extsEnv.Clone()
timeSampleExt = timeSampleExtEnv.SharedLibrary( 'TimeSample', Glob('*.cpp') ),
timeSampleManifest = timeSampleExtEnv.File( 'TimeSample.fpm.json' ),
timeSampleExtFiles = [timeSampleManifest, timeSampleExt]

Return( 'timeSampleExtFiles' )
